package co.com.ies.pruebas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAllPropertiesEquals(Model expected, Model actual) {
        assertModelAutoGeneratedPropertiesEquals(expected, actual);
        assertModelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAllUpdatablePropertiesEquals(Model expected, Model actual) {
        assertModelUpdatableFieldsEquals(expected, actual);
        assertModelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAutoGeneratedPropertiesEquals(Model expected, Model actual) {
        assertThat(expected)
            .as("Verify Model auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelUpdatableFieldsEquals(Model expected, Model actual) {
        assertThat(expected)
            .as("Verify Model relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelUpdatableRelationshipsEquals(Model expected, Model actual) {
        assertThat(expected)
            .as("Verify Model relationships")
            .satisfies(e -> assertThat(e.getManufacturer()).as("check manufacturer").isEqualTo(actual.getManufacturer()));
    }
}
